
@api_key= "97a0ecdf541080bcb45926a6ba81b292"

### get movie data
GET https://api.themoviedb.org/3/movie/550?api_key=97a0ecdf541080bcb45926a6ba81b292&language=zh-TW
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>


### search for movies
GET https://api.themoviedb.org/3/search/movie?api_key=97a0ecdf541080bcb45926a6ba81b292&query=fight+club
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>


### search movie detail by id
GET https://api.themoviedb.org/3/movie/550?api_key=97a0ecdf541080bcb45926a6ba81b292
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>


### search movie detail by id multi query
GET https://api.themoviedb.org/3/movie/343611?api_key=97a0ecdf541080bcb45926a6ba81b292&append_to_response=videos
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>


###What are the most popular movies?
GET https://api.themoviedb.org/3/movie/popular?api_key=97a0ecdf541080bcb45926a6ba81b292&language=en-US&page=1
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>


###discover movie
GET https://api.themoviedb.org/3/discover/movie?api_key=97a0ecdf541080bcb45926a6ba81b292&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=18
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>


###
GET https://api.themoviedb.org/3/discover/movie?api_key=97a0ecdf541080bcb45926a6ba81b292&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=28
Content-Type: application/json;charset=charset=utf-8'
Authorization: Bearer <<access_token>>